version: '3.4'
      
services:           
  pg.academic:
    image: postgres:14.2-alpine
    ports:
      - 7432:5432
    environment:
      POSTGRES_USER: grupoa
      POSTGRES_PASSWORD: V4Tc3^wZF46S&&E
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1500"
      - "-c"
      - "max_connections=500"
    volumes:
      - pg.academic.data:/var/lib/postgresql/data
            
volumes:
  pg.academic.data: